//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyalect.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkerErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkerErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dyalect.Strings.LinkerErrors", typeof(LinkerErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading module &quot;{0}&quot; from an assembly &quot;{1}&quot;: {2}.
        /// </summary>
        internal static string AssemblyModuleLoadError {
            get {
                return ResourceManager.GetString("AssemblyModuleLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module &quot;{0}&quot; is not defined in an assembly &quot;{1}&quot;..
        /// </summary>
        internal static string AssemblyModuleNotFound {
            get {
                return ResourceManager.GetString("AssemblyModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an assembly &quot;{0}&quot; (for a reference module &quot;{1}&quot;). .
        /// </summary>
        internal static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum validation of dependency &quot;{0}&quot; failed for module &quot;{1}&quot;. .
        /// </summary>
        internal static string ChecksumValidationFailed {
            get {
                return ResourceManager.GetString("ChecksumValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name of a module &quot;{1}&quot; in an assembly &quot;{0}&quot;..
        /// </summary>
        internal static string DuplicateModuleName {
            get {
                return ResourceManager.GetString("DuplicateModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate [VarArgs] attribute for method &quot;{0}&quot;..
        /// </summary>
        internal static string DuplicateVarArgs {
            get {
                return ResourceManager.GetString("DuplicateVarArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type of a module &quot;{0}&quot; from an assembly &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidAssemblyModule {
            get {
                return ResourceManager.GetString("InvalidAssemblyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find module &quot;{0}&quot;..
        /// </summary>
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of source file is available for module &quot;{0}&quot;..
        /// </summary>
        internal static string NewerSourceFile {
            get {
                return ResourceManager.GetString("NewerSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; has too many parameters..
        /// </summary>
        internal static string TooManyParameters {
            get {
                return ResourceManager.GetString("TooManyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading assembly &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string UnableLoadAssembly {
            get {
                return ResourceManager.GetString("UnableLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while reading module file &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string UnableReadModule {
            get {
                return ResourceManager.GetString("UnableReadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read object file &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string UnableReadObjectFile {
            get {
                return ResourceManager.GetString("UnableReadObjectFile", resourceCulture);
            }
        }
    }
}
