//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dyalect.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParserErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dyalect.Strings.ParserErrors", typeof(ParserErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code island inside of a string literal..
        /// </summary>
        internal static string CodeIslandInvalid {
            get {
                return ResourceManager.GetString("CodeIslandInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code islands are not allowed..
        /// </summary>
        internal static string CodeIslandsNotAllowed {
            get {
                return ResourceManager.GetString("CodeIslandsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid variable declaration..
        /// </summary>
        internal static string InvalidBinding {
            get {
                return ResourceManager.GetString("InvalidBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character literal..
        /// </summary>
        internal static string InvalidCharLiteral {
            get {
                return ResourceManager.GetString("InvalidCharLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized escape sequence..
        /// </summary>
        internal static string InvalidEscapeCode {
            get {
                return ResourceManager.GetString("InvalidEscapeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression..
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function expression..
        /// </summary>
        internal static string InvalidFunctionExpression {
            get {
                return ResourceManager.GetString("InvalidFunctionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function name..
        /// </summary>
        internal static string InvalidFunctionName {
            get {
                return ResourceManager.GetString("InvalidFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conditional operator..
        /// </summary>
        internal static string InvalidIf {
            get {
                return ResourceManager.GetString("InvalidIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid import statement..
        /// </summary>
        internal static string InvalidImport {
            get {
                return ResourceManager.GetString("InvalidImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax for a label..
        /// </summary>
        internal static string InvalidLabel {
            get {
                return ResourceManager.GetString("InvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid literal..
        /// </summary>
        internal static string InvalidLiteral {
            get {
                return ResourceManager.GetString("InvalidLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern is invalid..
        /// </summary>
        internal static string InvalidPattern {
            get {
                return ResourceManager.GetString("InvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operator..
        /// </summary>
        internal static string InvalidStandardOperators {
            get {
                return ResourceManager.GetString("InvalidStandardOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid statement..
        /// </summary>
        internal static string InvalidStatement {
            get {
                return ResourceManager.GetString("InvalidStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in expression or statement syntax: {0}.
        /// </summary>
        internal static string InvalidSyntax {
            get {
                return ResourceManager.GetString("InvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid try/catch expression..
        /// </summary>
        internal static string InvalidTryCatch {
            get {
                return ResourceManager.GetString("InvalidTryCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unary operator..
        /// </summary>
        internal static string InvalidUnary {
            get {
                return ResourceManager.GetString("InvalidUnary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic error: {0}.
        /// </summary>
        internal static string SemanticError {
            get {
                return ResourceManager.GetString("SemanticError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expected..
        /// </summary>
        internal static string TokenExpected {
            get {
                return ResourceManager.GetString("TokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined parser error..
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
    }
}
